using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for ASN_file_log
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class AsnFileLogController
    {
        // Preload our schema..
        AsnFileLog thisSchemaLoad = new AsnFileLog();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public AsnFileLogCollection FetchAll()
        {
            AsnFileLogCollection coll = new AsnFileLogCollection();
            Query qry = new Query(AsnFileLog.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public AsnFileLogCollection FetchByID(object LogId)
        {
            AsnFileLogCollection coll = new AsnFileLogCollection().Where("log_ID", LogId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public AsnFileLogCollection FetchByQuery(Query qry)
        {
            AsnFileLogCollection coll = new AsnFileLogCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object LogId)
        {
            return (AsnFileLog.Delete(LogId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object LogId)
        {
            return (AsnFileLog.Destroy(LogId) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? FileNumber,string FileName,DateTime? DateRequested,string RequestedBy,DateTime? DateUploaded,byte[] LogTs)
	    {
		    AsnFileLog item = new AsnFileLog();
		    
            item.FileNumber = FileNumber;
            
            item.FileName = FileName;
            
            item.DateRequested = DateRequested;
            
            item.RequestedBy = RequestedBy;
            
            item.DateUploaded = DateUploaded;
            
            item.LogTs = LogTs;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int LogId,int? FileNumber,string FileName,DateTime? DateRequested,string RequestedBy,DateTime? DateUploaded,byte[] LogTs)
	    {
		    AsnFileLog item = new AsnFileLog();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.LogId = LogId;
				
			item.FileNumber = FileNumber;
				
			item.FileName = FileName;
				
			item.DateRequested = DateRequested;
				
			item.RequestedBy = RequestedBy;
				
			item.DateUploaded = DateUploaded;
				
			item.LogTs = LogTs;
				
	        item.Save(UserName);
	    }
    }
}
