using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for B3LookupPrinterID
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class B3LookupPrinterIDController
    {
        // Preload our schema..
        B3LookupPrinterID thisSchemaLoad = new B3LookupPrinterID();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public B3LookupPrinterIDCollection FetchAll()
        {
            B3LookupPrinterIDCollection coll = new B3LookupPrinterIDCollection();
            Query qry = new Query(B3LookupPrinterID.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public B3LookupPrinterIDCollection FetchByID(object B3PrinterSupplierID)
        {
            B3LookupPrinterIDCollection coll = new B3LookupPrinterIDCollection().Where("B3PrinterSupplierID", B3PrinterSupplierID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public B3LookupPrinterIDCollection FetchByQuery(Query qry)
        {
            B3LookupPrinterIDCollection coll = new B3LookupPrinterIDCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object B3PrinterSupplierID)
        {
            return (B3LookupPrinterID.Delete(B3PrinterSupplierID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object B3PrinterSupplierID)
        {
            return (B3LookupPrinterID.Destroy(B3PrinterSupplierID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int B3PrinterSupplierID,int PrinterID)
	    {
		    B3LookupPrinterID item = new B3LookupPrinterID();
		    
            item.B3PrinterSupplierID = B3PrinterSupplierID;
            
            item.PrinterID = PrinterID;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int B3PrinterSupplierID,int PrinterID)
	    {
		    B3LookupPrinterID item = new B3LookupPrinterID();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.B3PrinterSupplierID = B3PrinterSupplierID;
				
			item.PrinterID = PrinterID;
				
	        item.Save(UserName);
	    }
    }
}
