using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for ContainerStatusTable
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class ContainerStatusTableController
    {
        // Preload our schema..
        ContainerStatusTable thisSchemaLoad = new ContainerStatusTable();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public ContainerStatusTableCollection FetchAll()
        {
            ContainerStatusTableCollection coll = new ContainerStatusTableCollection();
            Query qry = new Query(ContainerStatusTable.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public ContainerStatusTableCollection FetchByID(object ContainerStatusID)
        {
            ContainerStatusTableCollection coll = new ContainerStatusTableCollection().Where("ContainerStatusID", ContainerStatusID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public ContainerStatusTableCollection FetchByQuery(Query qry)
        {
            ContainerStatusTableCollection coll = new ContainerStatusTableCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object ContainerStatusID)
        {
            return (ContainerStatusTable.Delete(ContainerStatusID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object ContainerStatusID)
        {
            return (ContainerStatusTable.Destroy(ContainerStatusID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string ContainerStatus)
	    {
		    ContainerStatusTable item = new ContainerStatusTable();
		    
            item.ContainerStatus = ContainerStatus;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int ContainerStatusID,string ContainerStatus)
	    {
		    ContainerStatusTable item = new ContainerStatusTable();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.ContainerStatusID = ContainerStatusID;
				
			item.ContainerStatus = ContainerStatus;
				
	        item.Save(UserName);
	    }
    }
}
