using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for CourierDetailsSubTable
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class CourierDetailsSubTableController
    {
        // Preload our schema..
        CourierDetailsSubTable thisSchemaLoad = new CourierDetailsSubTable();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public CourierDetailsSubTableCollection FetchAll()
        {
            CourierDetailsSubTableCollection coll = new CourierDetailsSubTableCollection();
            Query qry = new Query(CourierDetailsSubTable.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public CourierDetailsSubTableCollection FetchByID(object CourierDetailID)
        {
            CourierDetailsSubTableCollection coll = new CourierDetailsSubTableCollection().Where("CourierDetailID", CourierDetailID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public CourierDetailsSubTableCollection FetchByQuery(Query qry)
        {
            CourierDetailsSubTableCollection coll = new CourierDetailsSubTableCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object CourierDetailID)
        {
            return (CourierDetailsSubTable.Delete(CourierDetailID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object CourierDetailID)
        {
            return (CourierDetailsSubTable.Destroy(CourierDetailID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? OrderNumber,int? DocsDespatchID,int? Original,DateTime? DocumentationDespatched,DateTime? DocsLastUpdated,string CourierName,string AWBNumber,bool SendByEmail,int? ContactID,string EmailAddress,byte[] Ts)
	    {
		    CourierDetailsSubTable item = new CourierDetailsSubTable();
		    
            item.OrderNumber = OrderNumber;
            
            item.DocsDespatchID = DocsDespatchID;
            
            item.Original = Original;
            
            item.DocumentationDespatched = DocumentationDespatched;
            
            item.DocsLastUpdated = DocsLastUpdated;
            
            item.CourierName = CourierName;
            
            item.AWBNumber = AWBNumber;
            
            item.SendByEmail = SendByEmail;
            
            item.ContactID = ContactID;
            
            item.EmailAddress = EmailAddress;
            
            item.Ts = Ts;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int CourierDetailID,int? OrderNumber,int? DocsDespatchID,int? Original,DateTime? DocumentationDespatched,DateTime? DocsLastUpdated,string CourierName,string AWBNumber,bool SendByEmail,int? ContactID,string EmailAddress,byte[] Ts)
	    {
		    CourierDetailsSubTable item = new CourierDetailsSubTable();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.CourierDetailID = CourierDetailID;
				
			item.OrderNumber = OrderNumber;
				
			item.DocsDespatchID = DocsDespatchID;
				
			item.Original = Original;
				
			item.DocumentationDespatched = DocumentationDespatched;
				
			item.DocsLastUpdated = DocsLastUpdated;
				
			item.CourierName = CourierName;
				
			item.AWBNumber = AWBNumber;
				
			item.SendByEmail = SendByEmail;
				
			item.ContactID = ContactID;
				
			item.EmailAddress = EmailAddress;
				
			item.Ts = Ts;
				
	        item.Save(UserName);
	    }
    }
}
