using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for despatch_note_pallet_ids
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class DespatchNotePalletIdController
    {
        // Preload our schema..
        DespatchNotePalletId thisSchemaLoad = new DespatchNotePalletId();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public DespatchNotePalletIdCollection FetchAll()
        {
            DespatchNotePalletIdCollection coll = new DespatchNotePalletIdCollection();
            Query qry = new Query(DespatchNotePalletId.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public DespatchNotePalletIdCollection FetchByID(object PalletId)
        {
            DespatchNotePalletIdCollection coll = new DespatchNotePalletIdCollection().Where("pallet_id", PalletId).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public DespatchNotePalletIdCollection FetchByQuery(Query qry)
        {
            DespatchNotePalletIdCollection coll = new DespatchNotePalletIdCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object PalletId)
        {
            return (DespatchNotePalletId.Delete(PalletId) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object PalletId)
        {
            return (DespatchNotePalletId.Destroy(PalletId) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int DespatchItemId,string Sscc,string PalletType,byte[] PalletTs)
	    {
		    DespatchNotePalletId item = new DespatchNotePalletId();
		    
            item.DespatchItemId = DespatchItemId;
            
            item.Sscc = Sscc;
            
            item.PalletType = PalletType;
            
            item.PalletTs = PalletTs;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int PalletId,int DespatchItemId,string Sscc,string PalletType,byte[] PalletTs)
	    {
		    DespatchNotePalletId item = new DespatchNotePalletId();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.PalletId = PalletId;
				
			item.DespatchItemId = DespatchItemId;
				
			item.Sscc = Sscc;
				
			item.PalletType = PalletType;
				
			item.PalletTs = PalletTs;
				
	        item.Save(UserName);
	    }
    }
}
