using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
	/// <summary>
	/// Strongly-typed collection for the FilterCompany class.
	/// </summary>
    [Serializable]
	public partial class FilterCompanyCollection : ActiveList<FilterCompany, FilterCompanyCollection>
	{	   
		public FilterCompanyCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>FilterCompanyCollection</returns>
		public FilterCompanyCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                FilterCompany o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the filter_companies table.
	/// </summary>
	[Serializable]
	public partial class FilterCompany : ActiveRecord<FilterCompany>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public FilterCompany()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public FilterCompany(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public FilterCompany(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public FilterCompany(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("filter_companies", TableType.Table, DataService.GetInstance("WWIprov"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarFilterID = new TableSchema.TableColumn(schema);
				colvarFilterID.ColumnName = "FilterID";
				colvarFilterID.DataType = DbType.Int32;
				colvarFilterID.MaxLength = 0;
				colvarFilterID.AutoIncrement = true;
				colvarFilterID.IsNullable = false;
				colvarFilterID.IsPrimaryKey = true;
				colvarFilterID.IsForeignKey = false;
				colvarFilterID.IsReadOnly = false;
				colvarFilterID.DefaultSetting = @"";
				colvarFilterID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFilterID);
				
				TableSchema.TableColumn colvarFilterCompanyID = new TableSchema.TableColumn(schema);
				colvarFilterCompanyID.ColumnName = "FilterCompanyID";
				colvarFilterCompanyID.DataType = DbType.Int32;
				colvarFilterCompanyID.MaxLength = 0;
				colvarFilterCompanyID.AutoIncrement = false;
				colvarFilterCompanyID.IsNullable = true;
				colvarFilterCompanyID.IsPrimaryKey = false;
				colvarFilterCompanyID.IsForeignKey = false;
				colvarFilterCompanyID.IsReadOnly = false;
				
						colvarFilterCompanyID.DefaultSetting = @"((0))";
				colvarFilterCompanyID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFilterCompanyID);
				
				TableSchema.TableColumn colvarAppliesToCompanyID = new TableSchema.TableColumn(schema);
				colvarAppliesToCompanyID.ColumnName = "AppliesToCompanyID";
				colvarAppliesToCompanyID.DataType = DbType.Int32;
				colvarAppliesToCompanyID.MaxLength = 0;
				colvarAppliesToCompanyID.AutoIncrement = false;
				colvarAppliesToCompanyID.IsNullable = true;
				colvarAppliesToCompanyID.IsPrimaryKey = false;
				colvarAppliesToCompanyID.IsForeignKey = false;
				colvarAppliesToCompanyID.IsReadOnly = false;
				
						colvarAppliesToCompanyID.DefaultSetting = @"((0))";
				colvarAppliesToCompanyID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAppliesToCompanyID);
				
				TableSchema.TableColumn colvarFilterTS = new TableSchema.TableColumn(schema);
				colvarFilterTS.ColumnName = "FilterTS";
				colvarFilterTS.DataType = DbType.Binary;
				colvarFilterTS.MaxLength = 0;
				colvarFilterTS.AutoIncrement = false;
				colvarFilterTS.IsNullable = true;
				colvarFilterTS.IsPrimaryKey = false;
				colvarFilterTS.IsForeignKey = false;
				colvarFilterTS.IsReadOnly = true;
				colvarFilterTS.DefaultSetting = @"";
				colvarFilterTS.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFilterTS);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["WWIprov"].AddSchema("filter_companies",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("FilterID")]
		[Bindable(true)]
		public int FilterID 
		{
			get { return GetColumnValue<int>(Columns.FilterID); }
			set { SetColumnValue(Columns.FilterID, value); }
		}
		  
		[XmlAttribute("FilterCompanyID")]
		[Bindable(true)]
		public int? FilterCompanyID 
		{
			get { return GetColumnValue<int?>(Columns.FilterCompanyID); }
			set { SetColumnValue(Columns.FilterCompanyID, value); }
		}
		  
		[XmlAttribute("AppliesToCompanyID")]
		[Bindable(true)]
		public int? AppliesToCompanyID 
		{
			get { return GetColumnValue<int?>(Columns.AppliesToCompanyID); }
			set { SetColumnValue(Columns.AppliesToCompanyID, value); }
		}
		  
		[XmlAttribute("FilterTS")]
		[Bindable(true)]
		public byte[] FilterTS 
		{
			get { return GetColumnValue<byte[]>(Columns.FilterTS); }
			set { SetColumnValue(Columns.FilterTS, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int? varFilterCompanyID,int? varAppliesToCompanyID,byte[] varFilterTS)
		{
			FilterCompany item = new FilterCompany();
			
			item.FilterCompanyID = varFilterCompanyID;
			
			item.AppliesToCompanyID = varAppliesToCompanyID;
			
			item.FilterTS = varFilterTS;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varFilterID,int? varFilterCompanyID,int? varAppliesToCompanyID,byte[] varFilterTS)
		{
			FilterCompany item = new FilterCompany();
			
				item.FilterID = varFilterID;
			
				item.FilterCompanyID = varFilterCompanyID;
			
				item.AppliesToCompanyID = varAppliesToCompanyID;
			
				item.FilterTS = varFilterTS;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn FilterIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn FilterCompanyIDColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn AppliesToCompanyIDColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn FilterTSColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string FilterID = @"FilterID";
			 public static string FilterCompanyID = @"FilterCompanyID";
			 public static string AppliesToCompanyID = @"AppliesToCompanyID";
			 public static string FilterTS = @"FilterTS";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
