using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
    /// <summary>
    /// Controller class for HouseBLTable
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class HouseBLTableController
    {
        // Preload our schema..
        HouseBLTable thisSchemaLoad = new HouseBLTable();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public HouseBLTableCollection FetchAll()
        {
            HouseBLTableCollection coll = new HouseBLTableCollection();
            Query qry = new Query(HouseBLTable.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public HouseBLTableCollection FetchByID(object HouseBLID)
        {
            HouseBLTableCollection coll = new HouseBLTableCollection().Where("HouseBLID", HouseBLID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public HouseBLTableCollection FetchByQuery(Query qry)
        {
            HouseBLTableCollection coll = new HouseBLTableCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object HouseBLID)
        {
            return (HouseBLTable.Delete(HouseBLID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object HouseBLID)
        {
            return (HouseBLTable.Destroy(HouseBLID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string HouseBLNumber,int? MasterBLID,int? ConsigneeID,DateTime? HBLDate,int? AgentAtDestinationID,int? OriginPort,int? DestinationPort,int? VoyageID,DateTime? Ets,DateTime? Eta,bool Added,byte[] Ts)
	    {
		    HouseBLTable item = new HouseBLTable();
		    
            item.HouseBLNumber = HouseBLNumber;
            
            item.MasterBLID = MasterBLID;
            
            item.ConsigneeID = ConsigneeID;
            
            item.HBLDate = HBLDate;
            
            item.AgentAtDestinationID = AgentAtDestinationID;
            
            item.OriginPort = OriginPort;
            
            item.DestinationPort = DestinationPort;
            
            item.VoyageID = VoyageID;
            
            item.Ets = Ets;
            
            item.Eta = Eta;
            
            item.Added = Added;
            
            item.Ts = Ts;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int HouseBLID,string HouseBLNumber,int? MasterBLID,int? ConsigneeID,DateTime? HBLDate,int? AgentAtDestinationID,int? OriginPort,int? DestinationPort,int? VoyageID,DateTime? Ets,DateTime? Eta,bool Added,byte[] Ts)
	    {
		    HouseBLTable item = new HouseBLTable();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.HouseBLID = HouseBLID;
				
			item.HouseBLNumber = HouseBLNumber;
				
			item.MasterBLID = MasterBLID;
				
			item.ConsigneeID = ConsigneeID;
				
			item.HBLDate = HBLDate;
				
			item.AgentAtDestinationID = AgentAtDestinationID;
				
			item.OriginPort = OriginPort;
				
			item.DestinationPort = DestinationPort;
				
			item.VoyageID = VoyageID;
				
			item.Ets = Ets;
				
			item.Eta = Eta;
				
			item.Added = Added;
				
			item.Ts = Ts;
				
	        item.Save(UserName);
	    }
    }
}
