using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
	/// <summary>
	/// Strongly-typed collection for the InvoiceSubTableAudit class.
	/// </summary>
    [Serializable]
	public partial class InvoiceSubTableAuditCollection : ActiveList<InvoiceSubTableAudit, InvoiceSubTableAuditCollection>
	{	   
		public InvoiceSubTableAuditCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>InvoiceSubTableAuditCollection</returns>
		public InvoiceSubTableAuditCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                InvoiceSubTableAudit o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the InvoiceSubTableAudit table.
	/// </summary>
	[Serializable]
	public partial class InvoiceSubTableAudit : ActiveRecord<InvoiceSubTableAudit>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public InvoiceSubTableAudit()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public InvoiceSubTableAudit(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public InvoiceSubTableAudit(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public InvoiceSubTableAudit(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("InvoiceSubTableAudit", TableType.Table, DataService.GetInstance("WWIprov"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarInvoiceSubTableAuditID = new TableSchema.TableColumn(schema);
				colvarInvoiceSubTableAuditID.ColumnName = "InvoiceSubTableAuditID";
				colvarInvoiceSubTableAuditID.DataType = DbType.Int32;
				colvarInvoiceSubTableAuditID.MaxLength = 0;
				colvarInvoiceSubTableAuditID.AutoIncrement = false;
				colvarInvoiceSubTableAuditID.IsNullable = false;
				colvarInvoiceSubTableAuditID.IsPrimaryKey = true;
				colvarInvoiceSubTableAuditID.IsForeignKey = false;
				colvarInvoiceSubTableAuditID.IsReadOnly = false;
				colvarInvoiceSubTableAuditID.DefaultSetting = @"";
				colvarInvoiceSubTableAuditID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInvoiceSubTableAuditID);
				
				TableSchema.TableColumn colvarInvoiceSubTableID = new TableSchema.TableColumn(schema);
				colvarInvoiceSubTableID.ColumnName = "InvoiceSubTableID";
				colvarInvoiceSubTableID.DataType = DbType.Int32;
				colvarInvoiceSubTableID.MaxLength = 0;
				colvarInvoiceSubTableID.AutoIncrement = false;
				colvarInvoiceSubTableID.IsNullable = true;
				colvarInvoiceSubTableID.IsPrimaryKey = false;
				colvarInvoiceSubTableID.IsForeignKey = true;
				colvarInvoiceSubTableID.IsReadOnly = false;
				colvarInvoiceSubTableID.DefaultSetting = @"";
				
					colvarInvoiceSubTableID.ForeignKeyTableName = "InvoiceSubTable";
				schema.Columns.Add(colvarInvoiceSubTableID);
				
				TableSchema.TableColumn colvarInvoiceNumber = new TableSchema.TableColumn(schema);
				colvarInvoiceNumber.ColumnName = "InvoiceNumber";
				colvarInvoiceNumber.DataType = DbType.Int32;
				colvarInvoiceNumber.MaxLength = 0;
				colvarInvoiceNumber.AutoIncrement = false;
				colvarInvoiceNumber.IsNullable = true;
				colvarInvoiceNumber.IsPrimaryKey = false;
				colvarInvoiceNumber.IsForeignKey = false;
				colvarInvoiceNumber.IsReadOnly = false;
				colvarInvoiceNumber.DefaultSetting = @"";
				colvarInvoiceNumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarInvoiceNumber);
				
				TableSchema.TableColumn colvarChargeType = new TableSchema.TableColumn(schema);
				colvarChargeType.ColumnName = "ChargeType";
				colvarChargeType.DataType = DbType.Int32;
				colvarChargeType.MaxLength = 0;
				colvarChargeType.AutoIncrement = false;
				colvarChargeType.IsNullable = true;
				colvarChargeType.IsPrimaryKey = false;
				colvarChargeType.IsForeignKey = false;
				colvarChargeType.IsReadOnly = false;
				colvarChargeType.DefaultSetting = @"";
				colvarChargeType.ForeignKeyTableName = "";
				schema.Columns.Add(colvarChargeType);
				
				TableSchema.TableColumn colvarDetail = new TableSchema.TableColumn(schema);
				colvarDetail.ColumnName = "Detail";
				colvarDetail.DataType = DbType.String;
				colvarDetail.MaxLength = 50;
				colvarDetail.AutoIncrement = false;
				colvarDetail.IsNullable = true;
				colvarDetail.IsPrimaryKey = false;
				colvarDetail.IsForeignKey = false;
				colvarDetail.IsReadOnly = false;
				colvarDetail.DefaultSetting = @"";
				colvarDetail.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDetail);
				
				TableSchema.TableColumn colvarOldValue = new TableSchema.TableColumn(schema);
				colvarOldValue.ColumnName = "OldValue";
				colvarOldValue.DataType = DbType.Int32;
				colvarOldValue.MaxLength = 0;
				colvarOldValue.AutoIncrement = false;
				colvarOldValue.IsNullable = true;
				colvarOldValue.IsPrimaryKey = false;
				colvarOldValue.IsForeignKey = false;
				colvarOldValue.IsReadOnly = false;
				colvarOldValue.DefaultSetting = @"";
				colvarOldValue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOldValue);
				
				TableSchema.TableColumn colvarNewValue = new TableSchema.TableColumn(schema);
				colvarNewValue.ColumnName = "NewValue";
				colvarNewValue.DataType = DbType.Single;
				colvarNewValue.MaxLength = 0;
				colvarNewValue.AutoIncrement = false;
				colvarNewValue.IsNullable = true;
				colvarNewValue.IsPrimaryKey = false;
				colvarNewValue.IsForeignKey = false;
				colvarNewValue.IsReadOnly = false;
				colvarNewValue.DefaultSetting = @"";
				colvarNewValue.ForeignKeyTableName = "";
				schema.Columns.Add(colvarNewValue);
				
				TableSchema.TableColumn colvarVat = new TableSchema.TableColumn(schema);
				colvarVat.ColumnName = "VAT";
				colvarVat.DataType = DbType.Boolean;
				colvarVat.MaxLength = 0;
				colvarVat.AutoIncrement = false;
				colvarVat.IsNullable = false;
				colvarVat.IsPrimaryKey = false;
				colvarVat.IsForeignKey = false;
				colvarVat.IsReadOnly = false;
				
						colvarVat.DefaultSetting = @"(0)";
				colvarVat.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVat);
				
				TableSchema.TableColumn colvarVATAmount = new TableSchema.TableColumn(schema);
				colvarVATAmount.ColumnName = "VATAmount";
				colvarVATAmount.DataType = DbType.Decimal;
				colvarVATAmount.MaxLength = 0;
				colvarVATAmount.AutoIncrement = false;
				colvarVATAmount.IsNullable = true;
				colvarVATAmount.IsPrimaryKey = false;
				colvarVATAmount.IsForeignKey = false;
				colvarVATAmount.IsReadOnly = false;
				colvarVATAmount.DefaultSetting = @"";
				colvarVATAmount.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVATAmount);
				
				TableSchema.TableColumn colvarDateAdded = new TableSchema.TableColumn(schema);
				colvarDateAdded.ColumnName = "DateAdded";
				colvarDateAdded.DataType = DbType.DateTime;
				colvarDateAdded.MaxLength = 0;
				colvarDateAdded.AutoIncrement = false;
				colvarDateAdded.IsNullable = true;
				colvarDateAdded.IsPrimaryKey = false;
				colvarDateAdded.IsForeignKey = false;
				colvarDateAdded.IsReadOnly = false;
				colvarDateAdded.DefaultSetting = @"";
				colvarDateAdded.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDateAdded);
				
				TableSchema.TableColumn colvarAddedBy = new TableSchema.TableColumn(schema);
				colvarAddedBy.ColumnName = "AddedBy";
				colvarAddedBy.DataType = DbType.Int32;
				colvarAddedBy.MaxLength = 0;
				colvarAddedBy.AutoIncrement = false;
				colvarAddedBy.IsNullable = true;
				colvarAddedBy.IsPrimaryKey = false;
				colvarAddedBy.IsForeignKey = false;
				colvarAddedBy.IsReadOnly = false;
				colvarAddedBy.DefaultSetting = @"";
				colvarAddedBy.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAddedBy);
				
				TableSchema.TableColumn colvarTs = new TableSchema.TableColumn(schema);
				colvarTs.ColumnName = "TS";
				colvarTs.DataType = DbType.Binary;
				colvarTs.MaxLength = 0;
				colvarTs.AutoIncrement = false;
				colvarTs.IsNullable = true;
				colvarTs.IsPrimaryKey = false;
				colvarTs.IsForeignKey = false;
				colvarTs.IsReadOnly = true;
				colvarTs.DefaultSetting = @"";
				colvarTs.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTs);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["WWIprov"].AddSchema("InvoiceSubTableAudit",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("InvoiceSubTableAuditID")]
		[Bindable(true)]
		public int InvoiceSubTableAuditID 
		{
			get { return GetColumnValue<int>(Columns.InvoiceSubTableAuditID); }
			set { SetColumnValue(Columns.InvoiceSubTableAuditID, value); }
		}
		  
		[XmlAttribute("InvoiceSubTableID")]
		[Bindable(true)]
		public int? InvoiceSubTableID 
		{
			get { return GetColumnValue<int?>(Columns.InvoiceSubTableID); }
			set { SetColumnValue(Columns.InvoiceSubTableID, value); }
		}
		  
		[XmlAttribute("InvoiceNumber")]
		[Bindable(true)]
		public int? InvoiceNumber 
		{
			get { return GetColumnValue<int?>(Columns.InvoiceNumber); }
			set { SetColumnValue(Columns.InvoiceNumber, value); }
		}
		  
		[XmlAttribute("ChargeType")]
		[Bindable(true)]
		public int? ChargeType 
		{
			get { return GetColumnValue<int?>(Columns.ChargeType); }
			set { SetColumnValue(Columns.ChargeType, value); }
		}
		  
		[XmlAttribute("Detail")]
		[Bindable(true)]
		public string Detail 
		{
			get { return GetColumnValue<string>(Columns.Detail); }
			set { SetColumnValue(Columns.Detail, value); }
		}
		  
		[XmlAttribute("OldValue")]
		[Bindable(true)]
		public int? OldValue 
		{
			get { return GetColumnValue<int?>(Columns.OldValue); }
			set { SetColumnValue(Columns.OldValue, value); }
		}
		  
		[XmlAttribute("NewValue")]
		[Bindable(true)]
		public float? NewValue 
		{
			get { return GetColumnValue<float?>(Columns.NewValue); }
			set { SetColumnValue(Columns.NewValue, value); }
		}
		  
		[XmlAttribute("Vat")]
		[Bindable(true)]
		public bool Vat 
		{
			get { return GetColumnValue<bool>(Columns.Vat); }
			set { SetColumnValue(Columns.Vat, value); }
		}
		  
		[XmlAttribute("VATAmount")]
		[Bindable(true)]
		public decimal? VATAmount 
		{
			get { return GetColumnValue<decimal?>(Columns.VATAmount); }
			set { SetColumnValue(Columns.VATAmount, value); }
		}
		  
		[XmlAttribute("DateAdded")]
		[Bindable(true)]
		public DateTime? DateAdded 
		{
			get { return GetColumnValue<DateTime?>(Columns.DateAdded); }
			set { SetColumnValue(Columns.DateAdded, value); }
		}
		  
		[XmlAttribute("AddedBy")]
		[Bindable(true)]
		public int? AddedBy 
		{
			get { return GetColumnValue<int?>(Columns.AddedBy); }
			set { SetColumnValue(Columns.AddedBy, value); }
		}
		  
		[XmlAttribute("Ts")]
		[Bindable(true)]
		public byte[] Ts 
		{
			get { return GetColumnValue<byte[]>(Columns.Ts); }
			set { SetColumnValue(Columns.Ts, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a InvoiceSubTable ActiveRecord object related to this InvoiceSubTableAudit
		/// 
		/// </summary>
		public DAL.Logistics.InvoiceSubTable InvoiceSubTable
		{
			get { return DAL.Logistics.InvoiceSubTable.FetchByID(this.InvoiceSubTableID); }
			set { SetColumnValue("InvoiceSubTableID", value.EntryNumber); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(int varInvoiceSubTableAuditID,int? varInvoiceSubTableID,int? varInvoiceNumber,int? varChargeType,string varDetail,int? varOldValue,float? varNewValue,bool varVat,decimal? varVATAmount,DateTime? varDateAdded,int? varAddedBy,byte[] varTs)
		{
			InvoiceSubTableAudit item = new InvoiceSubTableAudit();
			
			item.InvoiceSubTableAuditID = varInvoiceSubTableAuditID;
			
			item.InvoiceSubTableID = varInvoiceSubTableID;
			
			item.InvoiceNumber = varInvoiceNumber;
			
			item.ChargeType = varChargeType;
			
			item.Detail = varDetail;
			
			item.OldValue = varOldValue;
			
			item.NewValue = varNewValue;
			
			item.Vat = varVat;
			
			item.VATAmount = varVATAmount;
			
			item.DateAdded = varDateAdded;
			
			item.AddedBy = varAddedBy;
			
			item.Ts = varTs;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varInvoiceSubTableAuditID,int? varInvoiceSubTableID,int? varInvoiceNumber,int? varChargeType,string varDetail,int? varOldValue,float? varNewValue,bool varVat,decimal? varVATAmount,DateTime? varDateAdded,int? varAddedBy,byte[] varTs)
		{
			InvoiceSubTableAudit item = new InvoiceSubTableAudit();
			
				item.InvoiceSubTableAuditID = varInvoiceSubTableAuditID;
			
				item.InvoiceSubTableID = varInvoiceSubTableID;
			
				item.InvoiceNumber = varInvoiceNumber;
			
				item.ChargeType = varChargeType;
			
				item.Detail = varDetail;
			
				item.OldValue = varOldValue;
			
				item.NewValue = varNewValue;
			
				item.Vat = varVat;
			
				item.VATAmount = varVATAmount;
			
				item.DateAdded = varDateAdded;
			
				item.AddedBy = varAddedBy;
			
				item.Ts = varTs;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn InvoiceSubTableAuditIDColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn InvoiceSubTableIDColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn InvoiceNumberColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn ChargeTypeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn DetailColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn OldValueColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn NewValueColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn VatColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn VATAmountColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn DateAddedColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn AddedByColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn TsColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string InvoiceSubTableAuditID = @"InvoiceSubTableAuditID";
			 public static string InvoiceSubTableID = @"InvoiceSubTableID";
			 public static string InvoiceNumber = @"InvoiceNumber";
			 public static string ChargeType = @"ChargeType";
			 public static string Detail = @"Detail";
			 public static string OldValue = @"OldValue";
			 public static string NewValue = @"NewValue";
			 public static string Vat = @"VAT";
			 public static string VATAmount = @"VATAmount";
			 public static string DateAdded = @"DateAdded";
			 public static string AddedBy = @"AddedBy";
			 public static string Ts = @"TS";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
