using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.Logistics
{
	/// <summary>
	/// Strongly-typed collection for the MasterBLTable class.
	/// </summary>
    [Serializable]
	public partial class MasterBLTableCollection : ActiveList<MasterBLTable, MasterBLTableCollection>
	{	   
		public MasterBLTableCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>MasterBLTableCollection</returns>
		public MasterBLTableCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                MasterBLTable o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the MasterBLTable table.
	/// </summary>
	[Serializable]
	public partial class MasterBLTable : ActiveRecord<MasterBLTable>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public MasterBLTable()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public MasterBLTable(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public MasterBLTable(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public MasterBLTable(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("MasterBLTable", TableType.Table, DataService.GetInstance("WWIprov"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarMblid = new TableSchema.TableColumn(schema);
				colvarMblid.ColumnName = "MBLID";
				colvarMblid.DataType = DbType.Int32;
				colvarMblid.MaxLength = 0;
				colvarMblid.AutoIncrement = true;
				colvarMblid.IsNullable = false;
				colvarMblid.IsPrimaryKey = true;
				colvarMblid.IsForeignKey = false;
				colvarMblid.IsReadOnly = false;
				colvarMblid.DefaultSetting = @"";
				colvarMblid.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMblid);
				
				TableSchema.TableColumn colvarMasterBLNumber = new TableSchema.TableColumn(schema);
				colvarMasterBLNumber.ColumnName = "MasterBLNumber";
				colvarMasterBLNumber.DataType = DbType.String;
				colvarMasterBLNumber.MaxLength = 50;
				colvarMasterBLNumber.AutoIncrement = false;
				colvarMasterBLNumber.IsNullable = true;
				colvarMasterBLNumber.IsPrimaryKey = false;
				colvarMasterBLNumber.IsForeignKey = false;
				colvarMasterBLNumber.IsReadOnly = false;
				colvarMasterBLNumber.DefaultSetting = @"";
				colvarMasterBLNumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMasterBLNumber);
				
				TableSchema.TableColumn colvarCarrier = new TableSchema.TableColumn(schema);
				colvarCarrier.ColumnName = "Carrier";
				colvarCarrier.DataType = DbType.Int32;
				colvarCarrier.MaxLength = 0;
				colvarCarrier.AutoIncrement = false;
				colvarCarrier.IsNullable = true;
				colvarCarrier.IsPrimaryKey = false;
				colvarCarrier.IsForeignKey = false;
				colvarCarrier.IsReadOnly = false;
				colvarCarrier.DefaultSetting = @"";
				colvarCarrier.ForeignKeyTableName = "";
				schema.Columns.Add(colvarCarrier);
				
				TableSchema.TableColumn colvarVoyageID = new TableSchema.TableColumn(schema);
				colvarVoyageID.ColumnName = "VoyageID";
				colvarVoyageID.DataType = DbType.Int32;
				colvarVoyageID.MaxLength = 0;
				colvarVoyageID.AutoIncrement = false;
				colvarVoyageID.IsNullable = true;
				colvarVoyageID.IsPrimaryKey = false;
				colvarVoyageID.IsForeignKey = false;
				colvarVoyageID.IsReadOnly = false;
				colvarVoyageID.DefaultSetting = @"";
				colvarVoyageID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarVoyageID);
				
				TableSchema.TableColumn colvarOriginPortID = new TableSchema.TableColumn(schema);
				colvarOriginPortID.ColumnName = "OriginPortID";
				colvarOriginPortID.DataType = DbType.Int32;
				colvarOriginPortID.MaxLength = 0;
				colvarOriginPortID.AutoIncrement = false;
				colvarOriginPortID.IsNullable = true;
				colvarOriginPortID.IsPrimaryKey = false;
				colvarOriginPortID.IsForeignKey = false;
				colvarOriginPortID.IsReadOnly = false;
				colvarOriginPortID.DefaultSetting = @"";
				colvarOriginPortID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarOriginPortID);
				
				TableSchema.TableColumn colvarDestinationPortID = new TableSchema.TableColumn(schema);
				colvarDestinationPortID.ColumnName = "DestinationPortID";
				colvarDestinationPortID.DataType = DbType.Int32;
				colvarDestinationPortID.MaxLength = 0;
				colvarDestinationPortID.AutoIncrement = false;
				colvarDestinationPortID.IsNullable = true;
				colvarDestinationPortID.IsPrimaryKey = false;
				colvarDestinationPortID.IsForeignKey = false;
				colvarDestinationPortID.IsReadOnly = false;
				colvarDestinationPortID.DefaultSetting = @"";
				colvarDestinationPortID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarDestinationPortID);
				
				TableSchema.TableColumn colvarEts = new TableSchema.TableColumn(schema);
				colvarEts.ColumnName = "ETS";
				colvarEts.DataType = DbType.DateTime;
				colvarEts.MaxLength = 0;
				colvarEts.AutoIncrement = false;
				colvarEts.IsNullable = true;
				colvarEts.IsPrimaryKey = false;
				colvarEts.IsForeignKey = false;
				colvarEts.IsReadOnly = false;
				colvarEts.DefaultSetting = @"";
				colvarEts.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEts);
				
				TableSchema.TableColumn colvarEta = new TableSchema.TableColumn(schema);
				colvarEta.ColumnName = "ETA";
				colvarEta.DataType = DbType.DateTime;
				colvarEta.MaxLength = 0;
				colvarEta.AutoIncrement = false;
				colvarEta.IsNullable = true;
				colvarEta.IsPrimaryKey = false;
				colvarEta.IsForeignKey = false;
				colvarEta.IsReadOnly = false;
				colvarEta.DefaultSetting = @"";
				colvarEta.ForeignKeyTableName = "";
				schema.Columns.Add(colvarEta);
				
				TableSchema.TableColumn colvarMasterBLDate = new TableSchema.TableColumn(schema);
				colvarMasterBLDate.ColumnName = "MasterBLDate";
				colvarMasterBLDate.DataType = DbType.DateTime;
				colvarMasterBLDate.MaxLength = 0;
				colvarMasterBLDate.AutoIncrement = false;
				colvarMasterBLDate.IsNullable = true;
				colvarMasterBLDate.IsPrimaryKey = false;
				colvarMasterBLDate.IsForeignKey = false;
				colvarMasterBLDate.IsReadOnly = false;
				colvarMasterBLDate.DefaultSetting = @"";
				colvarMasterBLDate.ForeignKeyTableName = "";
				schema.Columns.Add(colvarMasterBLDate);
				
				TableSchema.TableColumn colvarConsigneeID = new TableSchema.TableColumn(schema);
				colvarConsigneeID.ColumnName = "ConsigneeID";
				colvarConsigneeID.DataType = DbType.Int32;
				colvarConsigneeID.MaxLength = 0;
				colvarConsigneeID.AutoIncrement = false;
				colvarConsigneeID.IsNullable = true;
				colvarConsigneeID.IsPrimaryKey = false;
				colvarConsigneeID.IsForeignKey = false;
				colvarConsigneeID.IsReadOnly = false;
				colvarConsigneeID.DefaultSetting = @"";
				colvarConsigneeID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarConsigneeID);
				
				TableSchema.TableColumn colvarAgentAtDestinationID = new TableSchema.TableColumn(schema);
				colvarAgentAtDestinationID.ColumnName = "AgentAtDestinationID";
				colvarAgentAtDestinationID.DataType = DbType.Int32;
				colvarAgentAtDestinationID.MaxLength = 0;
				colvarAgentAtDestinationID.AutoIncrement = false;
				colvarAgentAtDestinationID.IsNullable = true;
				colvarAgentAtDestinationID.IsPrimaryKey = false;
				colvarAgentAtDestinationID.IsForeignKey = false;
				colvarAgentAtDestinationID.IsReadOnly = false;
				colvarAgentAtDestinationID.DefaultSetting = @"";
				colvarAgentAtDestinationID.ForeignKeyTableName = "";
				schema.Columns.Add(colvarAgentAtDestinationID);
				
				TableSchema.TableColumn colvarTs = new TableSchema.TableColumn(schema);
				colvarTs.ColumnName = "TS";
				colvarTs.DataType = DbType.Binary;
				colvarTs.MaxLength = 0;
				colvarTs.AutoIncrement = false;
				colvarTs.IsNullable = true;
				colvarTs.IsPrimaryKey = false;
				colvarTs.IsForeignKey = false;
				colvarTs.IsReadOnly = true;
				colvarTs.DefaultSetting = @"";
				colvarTs.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTs);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["WWIprov"].AddSchema("MasterBLTable",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("Mblid")]
		[Bindable(true)]
		public int Mblid 
		{
			get { return GetColumnValue<int>(Columns.Mblid); }
			set { SetColumnValue(Columns.Mblid, value); }
		}
		  
		[XmlAttribute("MasterBLNumber")]
		[Bindable(true)]
		public string MasterBLNumber 
		{
			get { return GetColumnValue<string>(Columns.MasterBLNumber); }
			set { SetColumnValue(Columns.MasterBLNumber, value); }
		}
		  
		[XmlAttribute("Carrier")]
		[Bindable(true)]
		public int? Carrier 
		{
			get { return GetColumnValue<int?>(Columns.Carrier); }
			set { SetColumnValue(Columns.Carrier, value); }
		}
		  
		[XmlAttribute("VoyageID")]
		[Bindable(true)]
		public int? VoyageID 
		{
			get { return GetColumnValue<int?>(Columns.VoyageID); }
			set { SetColumnValue(Columns.VoyageID, value); }
		}
		  
		[XmlAttribute("OriginPortID")]
		[Bindable(true)]
		public int? OriginPortID 
		{
			get { return GetColumnValue<int?>(Columns.OriginPortID); }
			set { SetColumnValue(Columns.OriginPortID, value); }
		}
		  
		[XmlAttribute("DestinationPortID")]
		[Bindable(true)]
		public int? DestinationPortID 
		{
			get { return GetColumnValue<int?>(Columns.DestinationPortID); }
			set { SetColumnValue(Columns.DestinationPortID, value); }
		}
		  
		[XmlAttribute("Ets")]
		[Bindable(true)]
		public DateTime? Ets 
		{
			get { return GetColumnValue<DateTime?>(Columns.Ets); }
			set { SetColumnValue(Columns.Ets, value); }
		}
		  
		[XmlAttribute("Eta")]
		[Bindable(true)]
		public DateTime? Eta 
		{
			get { return GetColumnValue<DateTime?>(Columns.Eta); }
			set { SetColumnValue(Columns.Eta, value); }
		}
		  
		[XmlAttribute("MasterBLDate")]
		[Bindable(true)]
		public DateTime? MasterBLDate 
		{
			get { return GetColumnValue<DateTime?>(Columns.MasterBLDate); }
			set { SetColumnValue(Columns.MasterBLDate, value); }
		}
		  
		[XmlAttribute("ConsigneeID")]
		[Bindable(true)]
		public int? ConsigneeID 
		{
			get { return GetColumnValue<int?>(Columns.ConsigneeID); }
			set { SetColumnValue(Columns.ConsigneeID, value); }
		}
		  
		[XmlAttribute("AgentAtDestinationID")]
		[Bindable(true)]
		public int? AgentAtDestinationID 
		{
			get { return GetColumnValue<int?>(Columns.AgentAtDestinationID); }
			set { SetColumnValue(Columns.AgentAtDestinationID, value); }
		}
		  
		[XmlAttribute("Ts")]
		[Bindable(true)]
		public byte[] Ts 
		{
			get { return GetColumnValue<byte[]>(Columns.Ts); }
			set { SetColumnValue(Columns.Ts, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varMasterBLNumber,int? varCarrier,int? varVoyageID,int? varOriginPortID,int? varDestinationPortID,DateTime? varEts,DateTime? varEta,DateTime? varMasterBLDate,int? varConsigneeID,int? varAgentAtDestinationID,byte[] varTs)
		{
			MasterBLTable item = new MasterBLTable();
			
			item.MasterBLNumber = varMasterBLNumber;
			
			item.Carrier = varCarrier;
			
			item.VoyageID = varVoyageID;
			
			item.OriginPortID = varOriginPortID;
			
			item.DestinationPortID = varDestinationPortID;
			
			item.Ets = varEts;
			
			item.Eta = varEta;
			
			item.MasterBLDate = varMasterBLDate;
			
			item.ConsigneeID = varConsigneeID;
			
			item.AgentAtDestinationID = varAgentAtDestinationID;
			
			item.Ts = varTs;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varMblid,string varMasterBLNumber,int? varCarrier,int? varVoyageID,int? varOriginPortID,int? varDestinationPortID,DateTime? varEts,DateTime? varEta,DateTime? varMasterBLDate,int? varConsigneeID,int? varAgentAtDestinationID,byte[] varTs)
		{
			MasterBLTable item = new MasterBLTable();
			
				item.Mblid = varMblid;
			
				item.MasterBLNumber = varMasterBLNumber;
			
				item.Carrier = varCarrier;
			
				item.VoyageID = varVoyageID;
			
				item.OriginPortID = varOriginPortID;
			
				item.DestinationPortID = varDestinationPortID;
			
				item.Ets = varEts;
			
				item.Eta = varEta;
			
				item.MasterBLDate = varMasterBLDate;
			
				item.ConsigneeID = varConsigneeID;
			
				item.AgentAtDestinationID = varAgentAtDestinationID;
			
				item.Ts = varTs;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn MblidColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn MasterBLNumberColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn CarrierColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn VoyageIDColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn OriginPortIDColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        public static TableSchema.TableColumn DestinationPortIDColumn
        {
            get { return Schema.Columns[5]; }
        }
        
        
        
        public static TableSchema.TableColumn EtsColumn
        {
            get { return Schema.Columns[6]; }
        }
        
        
        
        public static TableSchema.TableColumn EtaColumn
        {
            get { return Schema.Columns[7]; }
        }
        
        
        
        public static TableSchema.TableColumn MasterBLDateColumn
        {
            get { return Schema.Columns[8]; }
        }
        
        
        
        public static TableSchema.TableColumn ConsigneeIDColumn
        {
            get { return Schema.Columns[9]; }
        }
        
        
        
        public static TableSchema.TableColumn AgentAtDestinationIDColumn
        {
            get { return Schema.Columns[10]; }
        }
        
        
        
        public static TableSchema.TableColumn TsColumn
        {
            get { return Schema.Columns[11]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string Mblid = @"MBLID";
			 public static string MasterBLNumber = @"MasterBLNumber";
			 public static string Carrier = @"Carrier";
			 public static string VoyageID = @"VoyageID";
			 public static string OriginPortID = @"OriginPortID";
			 public static string DestinationPortID = @"DestinationPortID";
			 public static string Ets = @"ETS";
			 public static string Eta = @"ETA";
			 public static string MasterBLDate = @"MasterBLDate";
			 public static string ConsigneeID = @"ConsigneeID";
			 public static string AgentAtDestinationID = @"AgentAtDestinationID";
			 public static string Ts = @"TS";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
