using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace DAL.CustomerTarget
{
    /// <summary>
    /// Controller class for target_history
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TargetHistoryController
    {
        // Preload our schema..
        TargetHistory thisSchemaLoad = new TargetHistory();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TargetHistoryCollection FetchAll()
        {
            TargetHistoryCollection coll = new TargetHistoryCollection();
            Query qry = new Query(TargetHistory.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TargetHistoryCollection FetchByID(object HistoryID)
        {
            TargetHistoryCollection coll = new TargetHistoryCollection().Where("historyID", HistoryID).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TargetHistoryCollection FetchByQuery(Query qry)
        {
            TargetHistoryCollection coll = new TargetHistoryCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object HistoryID)
        {
            return (TargetHistory.Delete(HistoryID) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object HistoryID)
        {
            return (TargetHistory.Destroy(HistoryID) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int? IDtarget,DateTime? LogDate,string LogUser,string FieldName,string ChangedFrom,string ChangedTo,byte[] Dbtimestamp)
	    {
		    TargetHistory item = new TargetHistory();
		    
            item.IDtarget = IDtarget;
            
            item.LogDate = LogDate;
            
            item.LogUser = LogUser;
            
            item.FieldName = FieldName;
            
            item.ChangedFrom = ChangedFrom;
            
            item.ChangedTo = ChangedTo;
            
            item.Dbtimestamp = Dbtimestamp;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int HistoryID,int? IDtarget,DateTime? LogDate,string LogUser,string FieldName,string ChangedFrom,string ChangedTo,byte[] Dbtimestamp)
	    {
		    TargetHistory item = new TargetHistory();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.HistoryID = HistoryID;
				
			item.IDtarget = IDtarget;
				
			item.LogDate = LogDate;
				
			item.LogUser = LogUser;
				
			item.FieldName = FieldName;
				
			item.ChangedFrom = ChangedFrom;
				
			item.ChangedTo = ChangedTo;
				
			item.Dbtimestamp = Dbtimestamp;
				
	        item.Save(UserName);
	    }
    }
}
