<?xml version="1.0" encoding="utf-8"?>
<Database Name="PublishipSQL" Class="linq_view_deliveriesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WWISQL;Initial Catalog=PublishipSQL;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PublishipSQLConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.view_deliveries_by_ets_and_vessel" Method="view_deliveries_by_ets_and_vessel" IsComposable="true">
    <Parameter Name="startETS" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="jobClosed" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="view_deliveries_by_ets_and_vesselResult">
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Copies" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ISBN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExWorksDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookingReceived" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="CargoReady" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="vessel_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ETS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ETA" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ContainerNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="current_status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StatusDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status_on" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrderNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeliveryAddress" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstPPC" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="ActualPPC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ActPPC" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="client_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="delivery_to" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="delivery_addr1" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="delivery_postcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="delivery_telno" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="JobClosed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TitleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RemarksToCustomer" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ContainerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderIx" Type="System.String" DbType="VarChar(120)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>