<?xml version="1.0" encoding="utf-8"?>
<Database Name="PublishipSQL" Class="linq_vesselDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WWISQL;Initial Catalog=PublishipSQL;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PublishipSQLConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.VesselTable" Member="VesselTables">
    <Type Name="VesselTable">
      <Column Name="VesselID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VesselName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TS" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
    </Type>
  </Table>
</Database>