#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PublishipSQL")]
	public partial class linq_query_logDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdb_query_log(db_query_log instance);
    partial void Updatedb_query_log(db_query_log instance);
    partial void Deletedb_query_log(db_query_log instance);
    #endregion
		
		public linq_query_logDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PublishipSQLConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linq_query_logDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linq_query_logDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linq_query_logDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linq_query_logDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<db_query_log> db_query_logs
		{
			get
			{
				return this.GetTable<db_query_log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.db_query_log")]
	public partial class db_query_log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _qry_ID;
		
		private string _qry_desc;
		
		private string _qry_text;
		
		private System.Nullable<int> _by_employeeID;
		
		private System.Nullable<int> _by_contactID;
		
		private string _log_ip;
		
		private System.Nullable<System.DateTime> _log_qry_date;
		
		private string _qry_source;
		
		private System.Data.Linq.Binary _log_qry_ts;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onqry_IDChanging(int value);
    partial void Onqry_IDChanged();
    partial void Onqry_descChanging(string value);
    partial void Onqry_descChanged();
    partial void Onqry_textChanging(string value);
    partial void Onqry_textChanged();
    partial void Onby_employeeIDChanging(System.Nullable<int> value);
    partial void Onby_employeeIDChanged();
    partial void Onby_contactIDChanging(System.Nullable<int> value);
    partial void Onby_contactIDChanged();
    partial void Onlog_ipChanging(string value);
    partial void Onlog_ipChanged();
    partial void Onlog_qry_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlog_qry_dateChanged();
    partial void Onqry_sourceChanging(string value);
    partial void Onqry_sourceChanged();
    partial void Onlog_qry_tsChanging(System.Data.Linq.Binary value);
    partial void Onlog_qry_tsChanged();
    #endregion
		
		public db_query_log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qry_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public int qry_ID
		{
			get
			{
				return this._qry_ID;
			}
			set
			{
				if ((this._qry_ID != value))
				{
					this.Onqry_IDChanging(value);
					this.SendPropertyChanging();
					this._qry_ID = value;
					this.SendPropertyChanged("qry_ID");
					this.Onqry_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qry_desc", DbType="NVarChar(150) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string qry_desc
		{
			get
			{
				return this._qry_desc;
			}
			set
			{
				if ((this._qry_desc != value))
				{
					this.Onqry_descChanging(value);
					this.SendPropertyChanging();
					this._qry_desc = value;
					this.SendPropertyChanged("qry_desc");
					this.Onqry_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qry_text", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string qry_text
		{
			get
			{
				return this._qry_text;
			}
			set
			{
				if ((this._qry_text != value))
				{
					this.Onqry_textChanging(value);
					this.SendPropertyChanging();
					this._qry_text = value;
					this.SendPropertyChanged("qry_text");
					this.Onqry_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_by_employeeID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> by_employeeID
		{
			get
			{
				return this._by_employeeID;
			}
			set
			{
				if ((this._by_employeeID != value))
				{
					this.Onby_employeeIDChanging(value);
					this.SendPropertyChanging();
					this._by_employeeID = value;
					this.SendPropertyChanged("by_employeeID");
					this.Onby_employeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_by_contactID", DbType="Int", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> by_contactID
		{
			get
			{
				return this._by_contactID;
			}
			set
			{
				if ((this._by_contactID != value))
				{
					this.Onby_contactIDChanging(value);
					this.SendPropertyChanging();
					this._by_contactID = value;
					this.SendPropertyChanged("by_contactID");
					this.Onby_contactIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_ip", DbType="NVarChar(20)", UpdateCheck=UpdateCheck.Never)]
		public string log_ip
		{
			get
			{
				return this._log_ip;
			}
			set
			{
				if ((this._log_ip != value))
				{
					this.Onlog_ipChanging(value);
					this.SendPropertyChanging();
					this._log_ip = value;
					this.SendPropertyChanged("log_ip");
					this.Onlog_ipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_qry_date", DbType="DateTime", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<System.DateTime> log_qry_date
		{
			get
			{
				return this._log_qry_date;
			}
			set
			{
				if ((this._log_qry_date != value))
				{
					this.Onlog_qry_dateChanging(value);
					this.SendPropertyChanging();
					this._log_qry_date = value;
					this.SendPropertyChanged("log_qry_date");
					this.Onlog_qry_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qry_source", DbType="NVarChar(5)", UpdateCheck=UpdateCheck.Never)]
		public string qry_source
		{
			get
			{
				return this._qry_source;
			}
			set
			{
				if ((this._qry_source != value))
				{
					this.Onqry_sourceChanging(value);
					this.SendPropertyChanging();
					this._qry_source = value;
					this.SendPropertyChanged("qry_source");
					this.Onqry_sourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_qry_ts", AutoSync=AutoSync.Always, DbType="rowversion NOT NULL", CanBeNull=false, IsDbGenerated=true, IsVersion=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary log_qry_ts
		{
			get
			{
				return this._log_qry_ts;
			}
			set
			{
				if ((this._log_qry_ts != value))
				{
					this.Onlog_qry_tsChanging(value);
					this.SendPropertyChanging();
					this._log_qry_ts = value;
					this.SendPropertyChanged("log_qry_ts");
					this.Onlog_qry_tsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
